import streamlit as st
import requests
import json
from datetime import datetime

st.set_page_config(page_title="NExUS - LECH Solidar", page_icon="✊", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
    <style>
        .cgsp-header { background: linear-gradient(135deg, #E2001A 0%, #c41817 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            .cgsp-header h1 { margin: 0; font-size: 2.5em; font-weight: bold; }
                .cgsp-header p { margin: 10px 0 0 0; font-size: 1.1em; opacity: 0.9; }
                    .compliance-vert { background-color: #d4edda; color: #155724; padding: 12px; border-radius: 5px; font-weight: bold; }
                        .compliance-rouge { background-color: #f8d7da; color: #721c24; padding: 12px; border-radius: 5px; font-weight: bold; }
                            .source-box { background-color: #e7f3ff; border-left: 4px solid #0066cc; padding: 12px; margin: 10px 0; border-radius: 4px; }
                                </style>
                                    """, unsafe_allow_html=True)

                                    CLOUD_FUNCTION_URL = st.secrets.get("CLOUD_FUNCTION_URL", "")
                                    PROJECT_ID = st.secrets.get("PROJECT_ID", "")
                                    DATA_STORE_ID = st.secrets.get("DATA_STORE_ID", "")

                                    st.markdown('<div class="cgsp-header"><h1>✊ NExUS - LECH Solidar</h1><p>L\'Intelligence au service des Camarades</p></div>', unsafe_allow_html=True)

                                    st.markdown("### 🤝 Bienvenue Camarade\nAccédez à l'expertise collective sur les protocoles du CHU Brugmann.")

                                    with st.sidebar:
                                        st.markdown("### 📖 Guide d'Utilisation\n**1. Espace Consultation** - Posez vos questions\n**2. Espace Mobilisation** - Générez des tracts\n**Principes:** ✅ Exactitude | ✅ Accessibilité | ✅ Transparence")

                                        tab1, tab2 = st.tabs(["💬 Chat de Consultation", "📱 Générateur de Mobilisation"])

                                        with tab1:
                                            st.markdown("### Posez votre question aux Protocoles")
                                                question = st.text_area("🎯 Votre question:", placeholder="Ex: Un stagiaire a-t-il droit à la prime?", height=80)
                                                    
                                                        if st.button("🔍 Interroger les Archives", use_container_width=True, type="primary"):
                                                                if question:
                                                                            with st.spinner("📚 Consultation des protocoles..."):
                                                                                            try:
                                                                                                                response = requests.post(CLOUD_FUNCTION_URL, json={"question": question, "project_id": PROJECT_ID, "data_store_id": DATA_STORE_ID}, timeout=30)
                                                                                                                                    if response.status_code == 200:
                                                                                                                                                            data = response.json()
                                                                                                                                                                                    if "fulfillment" in data:
                                                                                                                                                                                                                messages = data["fulfillment"].get("messages", [])
                                                                                                                                                                                                                                            if messages:
                                                                                                                                                                                                                                                                            st.markdown("### 📋 Réponse\n" + messages[0].get("text", ""))
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            compliance_score = data.get("compliance_score", 0)
                                                                                                                                                                                                                                                                                                                                                    violation = data.get("violation_detected", False)
                                                                                                                                                                                                                                                                                                                                                                            st.markdown("---")
                                                                                                                                                                                                                                                                                                                                                                                                    if violation:
                                                                                                                                                                                                                                                                                                                                                                                                                                st.markdown(f'<div class="compliance-rouge">⚠️ ALERTE | Score: {compliance_score}%</div>', unsafe_allow_html=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.markdown(f'<div class="compliance-vert">✅ Conforme | Score: {compliance_score}%</div>', unsafe_allow_html=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if "sources" in data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.markdown("**📚 Sources consultées:**")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for source in data.get("sources", []):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.markdown(f'<div class="source-box">📄 {source}</div>', unsafe_allow_html=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.error(f"❌ Erreur API: {response.status_code}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.error(f"❌ Erreur: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.warning("⚠️ Veuillez poser une question")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with tab2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.markdown("### 🚀 Générer des Messages de Mobilisation")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mobilization = st.text_area("📣 Contexte:", placeholder="Ex: Prime refusée", height=80)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            audience = st.selectbox("👥 Public:", ["Délégués", "Stagiaires", "Tous les camarades", "Permanents"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if st.button("✍️ Générer Tract", use_container_width=True, type="primary"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if mobilization:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.info(f"📱 Camarades!\n\nNouvelle action: {mobilization}\n\nPublic: {audience}\n\nRejoignez-nous! ✊")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.warning("⚠️ Décrivez le contexte")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.markdown('<div style="text-align: center; padding: 20px; color: #666; border-top: 1px solid #ddd; margin-top: 40px;"><p><strong>NExUS - LECH Solidar</strong> | Construit avec ❤️ pour CHU Brugmann | © 2025 CGSP</p></div>', unsafe_allow_html=True)